// Generates sql/seed/ipl.sql: a deterministic double round-robin of 5 teams for
// the 2024 season plus a few 2023 matches. Scores are synthetic and chosen to
// exercise the streak query's edge cases (see comments on each player).
// Run: node sql/seed/generate_ipl_seed.js
const fs = require('node:fs');
const path = require('node:path');

const teams = ['RCB', 'CSK', 'SRH', 'KKR', 'MI'];
const venues = { RCB: 'Bengaluru', CSK: 'Chennai', SRH: 'Hyderabad', KKR: 'Kolkata', MI: 'Mumbai' };

const players = [
  // id, name, team, 2024 scores in the team's match order (null = did not bat)
  [1, 'Virat Kohli', 'RCB', [21, 77, 83, 33, 22, 113, 42, 51]], // two separate 3-match streaks
  [2, 'Ruturaj Gaikwad', 'CSK', [15, 46, 1, 69, 67, 98, 62, 0]], // one 4-match streak
  [3, 'Travis Head', 'SRH', [32, 62, 31, 30, 0, 102, 11, 89]], // streak starts on first match; exactly 30 counts
  [4, 'Abhishek Sharma', 'SRH', [12, 63, 37, null, 40, 46, 75, 2]], // DNB breaks the first run; second run qualifies
  [5, 'Sunil Narine', 'KKR', [30, 47, 29, 85, 71, 10, 30, 31]], // 29 and short runs: never 3 in a row
  [6, 'Rohit Sharma', 'MI', [43, 26, 49, 38, 8, 105, 36, 4]], // only 2-match runs in 2024
];
// Rohit's 2023 streak (45, 38, 50) must NOT be reported for 2024.
const rohit2023 = [45, 38, 50];

// Circle-method round robin for 5 teams (one bye per round), played twice.
function roundRobin(list) {
  const t = [...list, 'BYE'];
  const rounds = [];
  for (let r = 0; r < t.length - 1; r++) {
    const pairs = [];
    for (let i = 0; i < t.length / 2; i++) {
      const a = t[i], b = t[t.length - 1 - i];
      if (a !== 'BYE' && b !== 'BYE') pairs.push(r % 2 ? [b, a] : [a, b]);
    }
    rounds.push(pairs);
    t.splice(1, 0, t.pop());
  }
  return rounds;
}

const fixtures = [...roundRobin(teams), ...roundRobin(teams).map((r) => r.map(([a, b]) => [b, a]))].flat();
const matches = [];
const start = new Date(Date.UTC(2024, 2, 22)); // 2024-03-22
fixtures.forEach(([home, away], i) => {
  const d = new Date(start);
  d.setUTCDate(start.getUTCDate() + i * 2);
  matches.push({ id: 101 + i, season: 2024, date: d.toISOString().slice(0, 10), home, away });
});
const m2023 = [
  { id: 1, season: 2023, date: '2023-04-08', home: 'MI', away: 'CSK' },
  { id: 2, season: 2023, date: '2023-04-11', home: 'MI', away: 'KKR' },
  { id: 3, season: 2023, date: '2023-04-16', home: 'SRH', away: 'MI' },
];

const scorecard = [];
for (const [id, , team, scores] of players) {
  const teamMatches = matches.filter((m) => m.home === team || m.away === team);
  if (teamMatches.length !== scores.length) throw new Error(`${team} plays ${teamMatches.length}, scores ${scores.length}`);
  teamMatches.forEach((m, i) => scorecard.push({ match: m.id, player: id, runs: scores[i] }));
}
m2023.forEach((m, i) => scorecard.push({ match: m.id, player: 6, runs: rohit2023[i] }));

const q = (s) => `'${s}'`;
const balls = (runs) => (runs === null ? 'NULL' : Math.max(1, Math.round(runs / 1.4)));
const sql = [
  '-- GENERATED by sql/seed/generate_ipl_seed.js — synthetic IPL-style data, not real scores.',
  'INSERT INTO players (player_id, player_name, team) VALUES',
  players.map(([id, name, team]) => `  (${id}, ${q(name)}, ${q(team)})`).join(',\n') + ';',
  '',
  'INSERT INTO matches (match_id, season, match_date, home_team, away_team, venue) VALUES',
  [...m2023, ...matches]
    .map((m) => `  (${m.id}, ${m.season}, ${q(m.date)}, ${q(m.home)}, ${q(m.away)}, ${q(venues[m.home])})`)
    .join(',\n') + ';',
  '',
  'INSERT INTO batting_scorecard (match_id, player_id, runs, balls) VALUES',
  scorecard.map((s) => `  (${s.match}, ${s.player}, ${s.runs === null ? 'NULL' : s.runs}, ${balls(s.runs)})`).join(',\n') + ';',
  '',
].join('\n');

fs.writeFileSync(path.join(__dirname, 'ipl.sql'), sql);
console.log(`Wrote ${matches.length + m2023.length} matches, ${scorecard.length} scorecard rows`);
